#!/usr/bin/env bash

cmd="$1"; shift
case "$cmd" in
-h|--help|"") cmd="help" ;;
--version) cmd="version" ;;
-*)
	echo "cg: unknown option '$cmd' (try 'cg --help' or 'cg --version')" >&2
	exit 1
esac

exe="cg-$cmd"
type -P "$exe" >/dev/null && exec "$exe" "$@"

echo "cg: unknown command '$cmd' (try 'cg help')" >&2
exit 1
