#!/usr/bin/env bash
#
# Rewrite GIT revision history.
# Copyright (c) Petr Baudis, 2006
#
# Lets you rewrite GIT revision history by creating a new branch from
# your current branch by applying custom filters on each revision.
# Those filters can modify each tree (e.g. removing a file or running
# a perl rewrite on all files) or information about each commit.
# Otherwise, all information (including original commit times or merge
# information) will be preserved.
#
# The command takes the new branch name as a mandatory argument and
# the filters as optional arguments. If you specify no filters, the
# commits will be recommitted without any changes, which would normally
# have no effect and result with the new branch pointing to the same
# branch as your current branch. (Nevertheless, this may be useful in
# the future for compensating for some Git bugs or such, therefore
# such a usage is permitted.)
#
# WARNING! The rewritten history will have different ids for all the
# objects and will not converge with the original branch. You will not
# be able to easily push and distribute the rewritten branch. Please do
# not use this command if you do not know the full implications, and
# avoid using it anyway - do not do what a simple single commit on top
# of the current version would fix.
#
# Always verify that the rewritten version is correct before disposing
# the original branch.
#
# OPTIONS
# -------
# -d TEMPDIR:: The path to the temporary tree used for rewriting
#	When applying a tree filter, the command needs to temporary
#	checkout the tree to some directory, which may consume
#	considerable space in case of large projects. By default it
#	does this in the '.git-rewrite/' directory but you can override
#	that choice by this parameter.
#
# -r STARTREV:: The commit id to start the rewrite at
#	Normally, the command will rewrite the entire history. If you
#	pass this argument, though, this will be the first commit it
#	will rewrite and keep the previous commits intact.
#
# Filters
# ~~~~~~~
# The filters are applied in the order as listed below. The COMMAND
# argument is always evaluated in shell using the 'eval' command.
# The $GIT_COMMIT environment variable is permanently set to contain
# the id of the commit being rewritten. The author/committer environment
# variables are set before the first filter is run.
#
# --env-filter COMMAND:: The filter for modifying environment
#	This is the filter for modifying the environment in which
#	the commit will be performed. Specifically, you might want
#	to rewrite the author/committer name/email/time environment
#	variables (see `cg-commit` for details). Do not forget to
#	re-export the variables.
#
# --tree-filter COMMAND:: The filter for rewriting tree (and its contents)
#	This is the filter for rewriting the tree and its contents.
#	The COMMAND argument is evaluated in shell with the working
#	directory set to the root of the checked out tree. The new tree
#	is then used as-is (new files are auto-added, disappeared files
#	are auto-removed - .gitignore files nor any other ignore rules
#	HAVE NO EFFECT!).
#
# --index-filter COMMAND:: The filter for rewriting index
#	This if the filter for rewriting the Git's directory index.
#	It is similar to the tree filter but does not check out the
#	tree, which makes it much faster. However, you must use the
#	lowlevel Git index manipulation commands to do your work.
#
# --msg-filter COMMAND:: The filter for rewriting commit message
#	This is the filter for rewriting the commit messages.
#	The COMMAND argument is evaluated in shell with the original
#	commit message on standard input; its standard output is
#
# EXAMPLE USAGE
# -------------
# Suppose you want to remove a file (containing confidental information
# or copyright violation) from all commits:
#
#	cg-admin-rewritehist --tree-filter 'rm filename' newbranch
#
# A significantly faster version:
#
#	cg-admin-rewritehist --index-filter 'git-update-index --remove filename' newbranch
#
# Now, you will get the rewritten history saved in the branch 'newbranch'
# (your current branch is left untouched).

USAGE="cg-admin-rewritehist [-d TEMPDIR] [-r STARTREV]... [FILTERS] DESTBRANCH"
_git_requires_root=1

. "${COGITO_LIB}"cg-Xlib || exit 1

tempdir=.git-rewrite
startrev=
filter_env=
filter_tree=
filter_index=
filter_msg=cat
while optparse; do
	if optparse -d=; then
		tempdir="$OPTARG"
	elif optparse -r=; then
		startrev="^$OPTARG $OPTARG $startrev"
	elif optparse --env-filter=; then
		filter_env="$OPTARG"
	elif optparse --tree-filter=; then
		filter_tree="$OPTARG"
	elif optparse --index-filter=; then
		filter_index="$OPTARG"
	elif optparse --msg-filter=; then
		filter_msg="$OPTARG"
	else
		optfail
	fi
done

dstbranch="${ARGS[0]}"
[ -n "$dstbranch" ] || die "missing branch name"
[ -s "$_git/refs/heads/$dstbranch" ] && die "branch $dstbranch already exists"
[ -s "$_git/branches/$dstbranch" ] && die "branch $dstbranch is already a remote branch"

[ -e "$tempdir" ] && die "$tempdir already exists, please remove it"
mkdir -p "$tempdir/t"
cd "$tempdir/t"

[ -n "$GIT_DIR" ] || export GIT_DIR=.git
[[ "$GIT_DIR" == /* ]] || export GIT_DIR="$(pwd)/../../$GIT_DIR"
export GIT_INDEX_FILE="$(pwd)/../index"
git-read-tree # seed the index file


mkdir ../map # map old->new commit ids for rewriting parents

git-rev-list --topo-order HEAD $startrev | tac >../revs
commits=$(cat ../revs | wc -l)

i=0
while read commit; do
	i=$((i+1))
	echo -n "$commit ($i/$commits) "

	git-read-tree -i -m $commit

	export GIT_COMMIT=$commit
	git-cat-file commit "$commit" >../commit

	eval "$(pick_author <../commit)"
	eval "$(pick_id committer COMMITTER <../commit)"
	eval "$filter_env"

	if [ "$filter_tree" ]; then
		git-checkout-index -f -u -a
		eval "$filter_tree"
		git-diff-index -r $commit | cut -f 2- | tr '\n' '\0' | \
			xargs -0 git-update-index --add --replace --remove
		git-ls-files --others | tr '\n' '\0' | \
			xargs -0 git-update-index --add --replace --remove
	fi

	eval "$filter_index"

	parentstr=
	for parent in $(cg-object-id -p $commit); do
		parentstr="$parentstr -p $(cat ../map/$parent)"
	done

	sed -e '1,/^$/d' <../commit | \
		eval "$filter_msg" | \
		git-commit-tree $(git-write-tree) $parentstr | \
		tee ../map/$commit
done <../revs

git-update-ref refs/heads/"$dstbranch" $(cat ../map/$(tail -n 1 ../revs))
cd ../..
rm -rf "$tempdir"
echo "Rewritten history saved to the $dstbranch branch"

exit 0
