#!/usr/bin/env bash
#
# Sets options regarding your local tree.
# Copyright (c) Petr Baudis, 2005
#
# Takes the option name and value name.

# XXX: This is now just original cg-track wrapped in nice clothing so that it
# can be used for something else too in the future.

die () {
	echo cg-admin-setopt: $@ >&2
	exit 1
}

option=$1; shift
[ "$option" = "update-default" ] || die "only 'update-default' option supported now"

name=$1
if [ ! "$name" ]; then
	rm .git/tracking
	exit
fi

[ -e .git/remotes ] || >.git/remotes
mkdir -p .git/heads

grep -q $(echo -e "^$name\t" | sed 's/\./\\./g') .git/remotes || \
	[ -s ".git/heads/$name" ] || \
	die "unknown branch \"$name\""

echo $name >.git/tracking
