#!/usr/bin/env bash
#
# List configured remote branches.
# Copyright (c) Steven Cole 2005
#
# Print a listing of all known branches.
#
# The output has the following format:
#
#	BRANCH LOCATION
# 
# For example
#
#	origin  http://www.kernel.org/pub/scm/cogito/cogito.git
#
# Terminology note: This command concerns remote branches, not the local
# ones (those managed by `cg-switch` and listed by `cg-status -g`).

USAGE="cg-branch-ls"
_git_wc_unneeded=1

. "${COGITO_LIB}"cg-Xlib || exit 1

mkdir -p "$_git/branches"
[ "$(find "$_git/branches" -follow -type f)" ] \
	|| die "list of branches is empty (see cg-branch-add(1))"

maxlen="$(find "$_git/branches" -name '*' -a ! -type d |
	  column_width "$_git/branches/")"

find "$_git/branches" -name '*' -a ! -type d | sort | while read branch; do
	name="${branch#$_git/branches/}"
	url="$(cat "$branch")"
	columns_print "$name" t$maxlen "$url" -
done
