#!/usr/bin/env bash
#
# Commit into a GIT repository.
# Copyright (c) Petr Baudis, 2005
# Based on an example script fragment sent to LKML by Linus Torvalds.
#
# Ignores any parameters for now, excepts changelog entry on stdin.
# -C makes git commit ignore cache and just commit the thing as-is;
# this is for internal purposes (merging).

. cg-Xlib


[ -s .git/blocked ] && die "committing blocked: $(cat .git/blocked)"

ignorecache=
if [ "$1" = "-C" ]; then
	ignorecache=1
	shift
fi

if [ "$1" ]; then
	commitfiles=("$@")
	customfiles="${commitfiles[*]}"

	[ "$ignorecache" ] && die "-C and listing files to commit does not make sense"
	[ -s .git/merging ] && die "cannot commit individual files when merging"

else
	# We bother with added/removed files here instead of updating
	# the cache at the time of cg-(add|rm), since we want to
	# have the cache in a consistent state representing the tree
	# as it was the last time we committed. Otherwise, e.g. partial
	# conflicts would be a PITA since added/removed files would
	# be committed along automagically as well.

	if [ ! "$ignorecache" ]; then
		eval changedfiles=($(git-diff-cache HEAD | cut -f 4- | \
			sed -e 's/^/"/' -e 's/$/"/'))
		commitfiles=($addedfiles $remfiles "${changedfiles[@]}")
	fi

	merging=
	[ -s .git/merging ] && merging=$(cat .git/merging | sed 's/^/-p /')
fi

LOGMSG=$(mktemp -t gitci.XXXXXX)
LOGMSG2=$(mktemp -t gitci2.XXXXXX)
echo CG: ---------------------------------------------------------- >>$LOGMSG
echo CG: Lines beggining with CG: will be automatically removed     >>$LOGMSG
echo CG:                                                            >>$LOGMSG
if [ ! "$ignorecache" ]; then
	if [ ! "${commitfiles[*]}" ]; then
		echo 'Nothing to commit.' >&2
		exit 2
	fi
	for file in "${commitfiles[@]}"; do
		# Prepend a letter describing whether it's addition,
		# removal or update. Or call git status on those files.
		echo CG: $file >>$LOGMSG
	done
	echo CG: >>$LOGMSG
fi

if [ "$merging" ]; then
	echo -n 'Merge with ' >>$LOGMSG
	[ -s .git/merging-sym ] || cp .git/merging .git/merging-sym
	for sym in $(cat .git/merging-sym); do
		uri=$(cat .git/branches/$sym)
		[ "$uri" ] || uri="$sym"
		echo "$uri" >>$LOGMSG
		echo "$uri"
	done
	echo >>$LOGMSG
fi
cp $LOGMSG $LOGMSG2
${EDITOR:-vi} $LOGMSG2
[ $LOGMSG2 -nt $LOGMSG ] || die 'Commit message not modified, commit aborted'
grep -v ^CG: $LOGMSG2 >$LOGMSG
rm $LOGMSG2

if [ ! "$ignorecache" ]; then
	if [ "$customfiles" ]; then
		git-update-cache --add --remove "${commitfiles[@]}" \
			|| die "update-cache failed"
		export GIT_INDEX_FILE=$(mktemp -t gitci.XXXXXX)
		git-read-tree HEAD
	fi
	# TODO: Do the proper separation of adds, removes, and changes.
	git-update-cache --add --remove "${commitfiles[@]}" \
		|| die "update-cache failed"
fi


oldhead=
if [ -s ".git/HEAD" ]; then
	oldhead=$(cat .git/HEAD)
	oldheadstr="-p $oldhead"
fi

treeid=$(git-write-tree)
[ "$treeid" ] || die "git-write-tree failed"
if [ ! "$merging" ] && [ "$oldhead" ] && [ "$treeid" = "$(tree-id)" ]; then
	echo "Refusing to make an empty commit - the tree was not modified" >&2
	echo "since the previous commit. If you really want to make the" >&2
	echo "commit, do: commit-tree \`tree-id\` -p \`parent-id\`" >&2
	exit 2;
fi

newhead=$(git-commit-tree $treeid $oldheadstr $merging <$LOGMSG)
rm $LOGMSG

if [ "$customfiles" ]; then
	rm $GIT_INDEX_FILE
	export GIT_INDEX_FILE=
fi

if [ "$newhead" ]; then
	echo "Committed as $newhead."
	echo $newhead >.git/HEAD
	[ "$merging" ] && rm .git/merging .git/merging-sym .git/merge-base
	exit 0
else
	die "error during commit (oldhead $oldhead, treeid $treeid)"
fi
