#!/usr/bin/env bash
#
# Clone a remote GIT repository.
# Copyright (c) Petr Baudis, 2005
#
# This is like cg-init, but it will create a new directory where it will do
# the checkout.
#
# Takes a parameter specifying the location of the source repository and an
# optional second parameter specifying the destination.  If the second
# parameter is omitted, the basename of the source repository is used as the
# destination.

. cg-Xlib

location=$1
[ "$location" ] || die "usage: cg-clone SOURCE_LOC [DESTDIR]"
location=${location%/}

destdir=$2
if [ "$destdir" ]; then
	dir=$destdir
else
	dir=${location%/.git}; dir=${dir##*/}
fi

if ! echo "$location" | grep -q ":" ; then
	location=$(echo "$location" | sed -e "s#^[^/]#$(pwd)\/&#")
else
	location="$location"
fi

[ -e "$dir" ] && die "$dir/ already exists"
mkdir "$dir" || exit $?
cd "$dir" || exit $?

cg-init $location || exit $?
echo "Cloned to $dir/ (origin $location available as branch \"origin\")"
