#!/usr/bin/env bash
#
# Initialize a GIT repository.
# Copyright (c) Petr Baudis, 2005
#
# Takes an optional parameter which will make it "clone" a specified
# remote repository.

. cg-Xlib

uri=$1

[ -e .git ] && die ".git already exists"

init-db
mkdir .git/heads .git/tags
touch .git/heads/master
ln -s heads/master .git/HEAD

if [ "$uri" ]; then
	echo -e "origin\t$uri" >.git/remotes
	cg-pull origin || die "pull failed"

	cp .git/heads/origin .git/heads/master
	read-tree $(tree-id)
	checkout-cache -a
	update-cache --refresh

	echo "Cloned $uri (origin available as branch \"origin\")"
fi
