#!/usr/bin/env bash
#
# Initialize a GIT repository.
# Copyright (c) Petr Baudis, 2005
#
# If `cg-init` is run in a non-empty directory files in the top and
# sub directory will automatically be added.
#
# OPTIONS
# -------
# -I::
#	Do not perform the initial commit.

USAGE="cg-init [-I]"
_git_repo_unneeded=1

. ${COGITO_LIB}cg-Xlib

no_initial_commit=
while optparse; do
	if optparse -I; then
		no_initial_commit=1
	else
		optfail
	fi
done

[ -e $_git ] && die "$_git already exists"

trap "rm -rf $_git; die \"interrupted\"" SIGINT SIGTERM

git-init-db
mkdir $_git/branches
touch $_git/refs/heads/master

git-read-tree # Seed the dircache
if ! [ "$no_initial_commit" ]; then
	find * \( -type f -o -type l \) -print0 | xargs -0r cg-add
	cg-commit -C -m"Initial commit" -E
fi

exit 0
