#!/usr/bin/env bash
#
# Pulls changes from remote branch to the local GIT repository.
# Copyright (c) Petr Baudis, 2005
#
# See cg-branch-add for some description.
#
# Takes the branch' name.

. cg-Xlib

name=$1


[ "$name" ] || die "where to pull from?"
uri=$(grep $(echo -e "^$name\t" | sed 's/\./\\./g') .git/remotes | cut -f 2)
[ "$uri" ] || die "unknown branch"

rembranch=master
if echo "$uri" | grep -q '#'; then
	rembranch=$(echo $uri | cut -d '#' -f 2)
	uri=$(echo $uri | cut -d '#' -f 1)
fi


fetch_rsync () {
	filter="cat"
	if [ "$1" = "-s" ]; then # subsequent
		# We already saw the MOTD, thank you very much.
		filter="grep -v ^MOTD:"
		shift
	fi

	rsync_flags_l=
	if [ "$1" = "-u" ]; then # update
		rsync_flags_l="--ignore-existing"
		shift
	fi

	appenduri=
	if [ "$1" = "-d" ]; then # directory
		appenduri="/." # CowboyNeal
		shift
	fi

	rsync $RSYNC_FLAGS $rsync_flags_l --whole-file -v -Lr \
		"$1$appenduri" "$2$appenduri" | $filter
}


orig_head=
[ -s ".git/heads/$name" ] && orig_head=$(cat ".git/heads/$name")


mkdir -p .git/heads
rsyncerr=
fetch_rsync "$uri/heads/$rembranch" ".git/heads/$name" 2>/dev/null || rsyncerr=1
if [ "$rsyncerr" ] && [ "$rembranch" = "master" ]; then
	rsyncerr=
	fetch_rsync -s "$uri/HEAD" ".git/heads/$name" || rsyncerr=1
fi
[ "$rsyncerr" ] && die "unable to get the head pointer of branch $rembranch"

[ -d .git/objects ] || mkdir -p .git/objects
fetch_rsync -s -u -d "$uri/objects/." ".git/objects/." || die "rsync error"

# FIXME: Warn about conflicting tag names?
# XXX: We now throw stderr to /dev/null since not all repositories
# may have tags/ and users were confused by the harmless errors.
[ -d .git/tags ] || mkdir -p .git/tags
fetch_rsync -s -u -d "$uri/tags/." ".git/tags/." 2>/dev/null || die "rsync error"


new_head=$(cat ".git/heads/$name")

if [ ! "$orig_head" ]; then
	echo "New branch: $new_head"

elif [ "$orig_head" != "$new_head" ]; then
	echo "Tree change: $orig_head:$new_head"
	diff-tree -r $(tree-id $orig_head) $(tree-id $new_head)

else
	echo "Up to date."
	exit
fi
