#!/usr/bin/env bash
#
# Remove a file from a GIT repository.
# Copyright (c) Petr Baudis, 2005
#
# Takes a list of file names at the command line, and schedules them
# for removal from the GIT repository at the next commit.

. ${COGITO_LIB}cg-Xlib

[ "$1" ] || die "usage: cg-rm FILE..."

rm -f "$@"
git-update-cache --remove -- "$@"
