#!/usr/bin/env bash
#
# Lists remote GIT repositories
# Copyright (c) Steven Cole 2005
#
# Takes no parameters

. cg-Xlib

[ -s .git/remotes ] || die "List of remotes is empty. See cg-remote-add."

cat .git/remotes
