#!/usr/bin/env bash
#
# Seek the working tree to a given commit.
# Copyright (c) Petr Baudis, 2005
#
# Takes the target commit ID to seek to as an argument.
# Seeking will bring the working tree from its current 'HEAD' to a given
# commit. Note that it changes just the 'HEAD' of the working tree, not
# the branch it is corresponding to. It will return to the 'HEAD' of
# the appropriate branch if passed no arguments.
#
# Therefore, for a quick excurse to the past of the 'master' branch:
#
#	$ cg-seek git-pasky-0.1
#	$ cg-diff this master	# will do the correct thing
#	$ cg-seek		# will restore what we had before
#
# For intuitiveness, specifying the branch name (`cg-seek master`) will do
# the right thing too. If you want to migrate your working tree to another
# branch, use `cg-clone`.

USAGE="cg-seek REVISION"

. ${COGITO_LIB}cg-Xlib

dstcommit=$1


[ -s $_git/blocked ] && grep -vq '^seeked from ' $_git/blocked && die "action blocked: $(cat $_git/blocked)"
if [ -s $_git/blocked ]; then
	branch=$(grep '^seeked from ' $_git/blocked | sed 's/^seeked from //')
else
	tmp=$(readlink $_git/HEAD)
	[ "$tmp" ] || die "HEAD is not on branch"
	branch=$(basename "$tmp")
fi

curcommit=$(commit-id)

if [ ! "$dstcommit" ] || [ "$dstcommit" = "$branch" ]; then
	rm $_git/HEAD
	ln -s "refs/heads/$branch" $_git/HEAD
	rm -f $_git/blocked
	dstcommit=$(commit-id)
else
	tmp=$(commit-id "$dstcommit")
	[ "$tmp" ] || die "branch $dstcommit not found"
	rm $_git/HEAD
	echo "$tmp" >$_git/HEAD
	[ -s $_git/blocked ] || echo "seeked from $branch" >$_git/blocked
fi

if [ "$curcommit" != "$dstcommit" ]; then
	echo l
	git-read-tree -m HEAD
	echo m
	cg-diff -r $curcommit:$dstcommit | cg-patch
	echo n
	git-update-cache --refresh
fi

echo "On commit $dstcommit"
