#!/usr/bin/env bash
#
# Seek the working tree to a given commit.
# Copyright (c) Petr Baudis, 2005
#
# This will bring the working tree from its current HEAD to a given
# commit. Note that it changes just the HEAD of the working tree, not
# the branch it is corresponding to. It will return to the HEAD of
# the appropriate branch if passed no arguments.
#
# Therefore, for a quick excurse to the past of the 'master' branch:
#
#	cg-seek git-pasky-0.1
#	cg-diff this master # will do the correct thing
#	cg-seek # will restore what we had before
#
# For intiutiveness, specifying the branch name (cg-seek master) will do
# the right thing too. If you want to migrate your working tree to another
# branch, use cg-fork.
#
# Takes the target commit ID.

. cg-Xlib

dstcommit=$1


[ -s .git/blocked ] && grep -vq '^seeked from ' .git/blocked && die "action blocked: $(cat .git/blocked)"
if [ -s .git/blocked ]; then
	branch=$(grep '^seeked from ' .git/blocked | sed 's/^seeked from //')
else
	tmp=$(readlink .git/HEAD)
	[ "$tmp" ] || die "HEAD is not on branch"
	branch=$(basename "$tmp")
fi

curcommit=$(commit-id)

if [ ! "$dstcommit" ] || [ "$dstcommit" = "$branch" ]; then
	rm .git/HEAD
	ln -s "refs/heads/$branch" .git/HEAD
	rm -f .git/blocked
	dstcommit=$(commit-id)
else
	tmp=$(commit-id "$dstcommit")
	[ "$tmp" ] || die "branch $dstcommit not found"
	rm .git/HEAD
	echo "$tmp" >.git/HEAD
	[ -s .git/blocked ] || echo "seeked from $branch" >.git/blocked
fi

if [ "$curcommit" != "$dstcommit" ]; then
	echo l
	git-read-tree -m HEAD
	echo m
	cg-diff -r $curcommit:$dstcommit | cg-patch
	echo n
	git-update-cache --refresh
fi

echo "On commit $dstcommit"
