#!/usr/bin/env bash
#
# Switch the working tree to another (possibly new) branch
# Copyright (c) Yann Dirson, 2005
#
# `cg-switch` allows to change the HEAD to another branch, and to
# create a new branch at a given point.
#
#   $ cg-switch v1.x v1.0              # creates a "1.x" branch at the v1.0 tag
#   $ cg-switch master                 # back to trunk
#   $ cg-switch -f master that-branch  # change "master" to refer to that-branch instead
#
# This tool is still much a work in progress.  Things to do include:
# - mode to create the branch only without really switching
# - deal with non-committed modifications before switch ?
# - allow switching "master" to another branch (-i for "in-place switch" ?)
# - safeguards to avoid problem when playing with remote branches ?

USAGE="cg-switch [-f] BRANCH [COMMIT_ID]"
_git_requires_root=1

. "${COGITO_LIB:-/export/work/yann/git/local/lib/cogito/}"cg-Xlib || exit 1

set -e

force=n
while optparse; do
    if optparse -f; then
	force=y
    else
	optfail
    fi
done

[ "$ARGS" ] || usage

dstlod=${ARGS[0]}
dstcommit=${ARGS[1]}

[ $(readlink $_git/HEAD) != "refs/heads/$dstlod" ] ||
    die "Already on branch \`$dstlod'"

do_change_branch() {
    cg-object-id -c $dstcommit > $_git/refs/heads/$dstlod
}

if [ $(git-rev-parse $dstlod) = "$dstlod" ]; then
    # not found
    [ -n "$dstcommit" ] ||
	die "Branch \`$dstlod' does not exists: please specify a branch-point to create it"
    [ $(git-rev-parse $dstcommit) != "$dstcommit" ] ||
	die "Cannot create branch on unknown ref \`$dstcommit'"
    echo "Creating new branch \`$dstlod'"
    do_change_branch
else
    # found
    [ -r "$_git/refs/heads/$dstlod" ] ||
	die "Ref \`$dstlod' already exists but is not a branch head"
    if [ -n "$dstcommit" ]; then
	if [ $force != y ]; then
	    die "Branch \`$dstlod' already exists - use -f to force switching it to \`$dstcommit'"
	fi
	do_change_branch
    fi
fi

# do seek
cg-seek "$dstlod"

# fixup things to get real branchs
rm $_git/HEAD
ln -s "refs/heads/$dstlod" $_git/HEAD
rm -f $_git/head-name $_git/refs/heads/cg-seek-point $_git/blocked
