#!/usr/bin/env bash
#
# Switch the working tree to another (possibly new) branch
# Copyright (c) Yann Dirson, 2005
#
# `cg-switch` allows to change the HEAD to another branch, and to
# create a new branch at a given point.
#
#   $ cg-switch -r v1.0 v1.x              # creates "1.x" branch and switch working copy to it
#   $ cg-switch -n -r v1.0 v1.x           # creates "1.x" branch without touching working copy
#   $ cg-switch master                    # back to trunk
#   $ cg-switch -f -r that-branch master  # change "master" to refer to that-branch instead
#
# This tool is still much a work in progress.  Things to do include:
# - deal with non-committed modifications before switch ?
# - safeguards to avoid problem when playing with remote branches ?

USAGE="cg-switch [-f] [-n] [-r COMMIT_ID] BRANCH"
_git_requires_root=1

. ${COGITO_LIB}cg-Xlib || exit 1

set -e

force=
seek=1
dstcommit=
while optparse; do
	if optparse -f; then
		force=1
	elif optparse -n; then
		seek=
	elif optparse -r=; then
		dstcommit="$OPTARG"
	else
		optfail
	fi
done

[ "$ARGS" ] || usage

dsthead="${ARGS[0]}"


do_change_branch() {
	git-update-ref "refs/heads/$dsthead" "$dstcommit"
}

is_branch_name() {
	[ -r "$_git/refs/heads/$1" ]
}

is_valid_ref() {
	[ "$(git-rev-parse "$1")" != "$1" ]
}


[ "$(git-symbolic-ref HEAD)" != "refs/heads/$dsthead" ] ||
	die "Already on branch '$dsthead'"

if ! is_branch_name "$dsthead"; then
	# not found
	[ -n "$dstcommit" ] ||
		die "Branch '$dsthead' does not exists: please specify a branch-point to create it"
	is_valid_ref "$dstcommit" ||
		die "Cannot create branch on unknown ref '$dstcommit'"
	echo "Creating new branch '$dsthead'"
	do_change_branch
else
	# found
	[ -r "$_git/refs/heads/$dsthead" ] ||
		die "Ref '$dsthead' already exists but is not a branch head"
	if [ -n "$dstcommit" ]; then
		[ "$force" ] ||
			die "Branch '$dsthead' already exists - use -f to force switching it to '$dstcommit'"
		echo "Moving branch '$dsthead'"
		do_change_branch
	fi
fi

if [ "$seek" ]; then
	cg-seek "$dsthead"

	# fixup things to get real branchs
	rm "$_git/HEAD"
	ln -s "refs/heads/$dsthead" "$_git/HEAD"
	rm -f "$_git/head-name" "$_git/refs/heads/cg-seek-point" "$_git/blocked"
fi
