#!/usr/bin/env bash
#
# Makes your working tree track the given branch.
# Copyright (c) Petr Baudis, 2005
#
# This script changes the default branch to be pulled/updated when
# those commands are called without any arguments.
#
# Takes the branch name. Without parameters lists the current default.

name=$1

die () {
	echo cg-remote-def: $@ >&2
	exit 1
}

[ "$name" ] || die "usage: cg-remote-def BRANCH"

[ -e .git/remotes ] || >.git/remotes
mkdir -p .git/heads

grep -q $(echo -e "^$name\t" | sed 's/\./\\./g') .git/remotes || \
	[ -s ".git/heads/$name" ] || \
	die "unknown branch \"$name\""

echo $name >.git/tracking
