#!/usr/bin/env bash
#
# List stored GIT tags.
# Copyright (c) Steve Hoelzer 2005
#
# Takes no parameters.

. ${COGITO_LIB}cg-Xlib

mkdir -p $_git/refs/tags
[ "$(find $_git/refs/tags -follow -type f)" ] \
       || die "List of tags is empty. See cg-tag."

cd $_git/refs/tags
for tag in *; do
       echo -n $tag
       echo -ne "\t"
       cat $tag
done
