#!/usr/bin/env bash
#
# Pulls changes from another branch to the local repository and merge changes.
# Copyright (c) Petr Baudis, 2005
#
# Takes the branch' name; no parameter will cause it to update
# against HEAD (only recovers lost files for now).

. cg-Xlib

name=$1
[ "$name" ] || die "where to update from?"

cg-pull $name || exit 1
echo
echo "Applying changes..."
cg-merge $name
