#!/usr/bin/env bash
#
# Get ID of commit associated with given id or HEAD.
# Copyright (c) Petr Baudis, 2005
#
# Takes the appropriate ID, defaults to HEAD.

id="$1"
normid=$(. ${COGITO_LIB}cg-Xnormid "$id") || exit 1
type=${normid#* }
normid=${normid% *}
[ "$type" ] || type=$(git-cat-file -t "$normid")

if [ "$type" != "commit" ]; then
	echo "Invalid commit id: $normid" >&2
	exit 1
fi

echo $normid
