#!/bin/sh
#
# The GIT scripted toolkit.
# Copyright (c) Petr Baudis, 2005
#
# This is the central command for the GIT toolkit, providing a humanly
# usable SCM-like interface to GIT.
#
# This command mostly only multiplexes to the individual script based
# on the first argument.

error () {
	echo git: $@ >&2
}
die () {
	error $@
	exit 1
}


help () {
	cat <<__END__
The GIT scripted toolkit  $(gitversion.sh)

Usage: git COMMAND [ARG]...

Available commands:
	add		FILE...
	addremote	RNAME RSYNC_URL
	apply				< patch on stdin
	cancel
	ci, commit	[FILE]...	< log message on stdin
	diff		[-p] [-r FROM_ID[:TO_ID]] [FILE]...
	export		DESTDIR [TREE_ID]
	fork		BNAME BRANCH_DIR [COMMIT_ID]
	help
	init		RSYNC_URL
	log		[COMMIT_ID | COMMIT_ID:COMMIT_ID]
	ls		[TREE_ID]
	lsobj		[OBJTYPE]
	lsremote
	merge		[-c] [-b BASE_ID] FROM_ID
	patch		[COMMIT_ID | COMMIT_ID:COMMIT_ID]
	pull		[RNAME]
	rm		FILE...
	seek		[COMMIT_ID]
	status
	tag		TNAME [COMMIT_ID]
	track		[RNAME]
	version

Note that these expressions can be used interchangably as "ID"s:
	empty string (current HEAD)
	remote name (as registered with git addremote)
	tag name (as registered with git tag)
	shortcut hash (shorted unambiguous hash lead)
	commit object hash (as returned by commit-id)
	tree object hash (accepted only by some commands)
__END__
}


cmd=$1; shift
if [ ! "$cmd" ]; then
	error "missing command"
	help
	exit 1
fi


case "$cmd" in
"add")        gitadd.sh "$@";;
"addremote")  gitaddremote.sh "$@";;
"apply")      gitapply.sh "$@";;
"cancel")     gitcancel.sh "$@";;
"ci" | "commit")
              gitcommit.sh "$@";;
"diff")       gitdiff.sh "$@";;
"export")     gitexport.sh "$@";;
"fork")       gitfork.sh "$@";;
"help")       help "$@";;
"init")       gitinit.sh "$@";;
"log")        gitlog.sh "$@";;
"ls")         gitls.sh "$@";;
"lsobj")      gitlsobj.sh "$@";;
"lsremote")   gitlsremote.sh "$@";;
"merge")      gitmerge.sh "$@";;
"pull")       gitpull.sh "$@";;
"patch")      gitpatch.sh "$@";;
"rm")         gitrm.sh "$@";;
"seek")       gitseek.sh "$@";;
"status")     gitstatus.sh "$@";;
"tag")        gittag.sh "$@";;
"track")      gittrack.sh "$@";;
"version")    gitversion.sh "$@";;
*)            error "unknown command"; help;;
esac
